# Generated by Django 6.0.8 on 2026-08-23 17:19

import salaz.models.recipe
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=salaz.models.recipe.recipe_image_upload_dir),
        ),
    ]
